name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "help wanted"]
assignees:
  - enricocid
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell me, what did you expect to happen?
      placeholder: Tell me what you see!
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of MPGO are you running?
      placeholder: 4.4.18
    validations:
      required: true
  - type: textarea
    id: device-android-version
    attributes:
      label: Device and Android version
      description: What is Your device/Android OS?
      placeholder: Xiaomi Mi A2/Android 10.0 (Lineage OS 17.1)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
  - type: textarea
    id: more-info
    attributes:
      label: More info
      description: Add more information to the bug report
      placeholder: For example, attach a screenshot or a screen recording
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to not yell at the developer if response is slow.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
